### PR TITLE
Added easy Colab notebook .ipynb and Colab link in Readme.md

### PR DESCRIPTION
**Pull request by Tylersuard**
**Patch description**
This adds a link to a Colab notebook for easy installation and use of the interactive version of this repo, as described on the Parl.ai website.

**Testing steps**
1.  Click the "Colab" shield at the top of Readme.md.
2.  Once the Colab notebook opens, switch runtime to GPU
3.  Execute all cells.  The 3B model should now run interactively.

### CODE REVIEW

**Comment by Tylersuard** [comment]
Why was this closed?  I would like this to be reviewed and if accepted, merged.

**Comment by stephenroller** [comment]
Thank you for your contribution. The bot closed it, but I've reopened it.

We're not used to colab notebooks being added to the repo and haven't had a chance to sort out some of the details. I'll make sure we discuss this in our next weekly meeting. I think a version of this will make it in, though we might opt for one that demonstrates how to do fine tuning.

**Comment by Tylersuard** [comment]
Thank you!

**Comment by stephenroller** [comment]
Going to add this myself soon, after the new parlai import magic lands. Will add a few colab tutorials and examples.

**Comment by SudoPseudo** [comment]
@stephenroller Thank you, I really appreciate it!

**Comment by Tylersuard** [comment]
Hello.  I'm sorry to trouble you again, I know you are very busy and you have important things to do.  I know it can take time and you want to be sure about someone's contributed code before you add it to your repo.  I was wondering if you would be available via zoom call, I can explain in 15 minutes what I did and how it adds value to the software.

**Comment by stephenroller** [comment]
I tried actually running this and it crashed. Probably because load the model fully into RAM instead of directly onto GPUs.

Gotta work around that somehow.

**Pull request closed without merging**
