### PR TITLE
Move threadpool to fixed data teacher

### PR DESCRIPTION
**Pull request by klshuster**
Moves the threadpool to fixed data teacher to provide threadpool data loading to any subclass of the fixed data teacher

### CODE REVIEW

**Comment by alexholdenmiller** [comment]
cool!

so I notice that it's still not very clear how to take advantage of this apart from copying code from VQA--it's not actually used by default from code within FixedData, right?

could we add in a basic example of how to use it in the docstring, in addition to the descriptions that you wrote?

**Comment by alexholdenmiller** [comment]
maybe we could include a parent implementation of the VQA image request?

**Comment by klshuster** [comment]
I can add an example to the teacher's docstring; by parent implementation, do you mean adding an implementation of the image request in VQA to the FixedDataTeacher

**Comment by jaseweston** [comment]
is this stuff going to work seamlessly  in the multitask case?

**Comment by klshuster** [comment]
from my initial testing, it seems to work in the multitask case

**Comment by jaseweston** [comment]
sweet!

**Comment by alexholdenmiller** [comment]
it will currently spawn n_threads per task--@klshuster we should try to guarantee only one threadpool is instantiated

**Pull request merged**
