### PR TITLE
Add end-to-end negotiation task

### PR DESCRIPTION
**Pull request by swkrueger**
Add end-to-end negotiation task that loads data from https://github.com/facebookresearch/end-to-end-negotiator.

### CODE REVIEW

**Comment by 1nadequacy** [comment]
Hey @swkrueger, thanks for doing this!

I took a look at your diff and it seems that you are only providing a way to perform the dialogue part of negotiation, since I wasn't able to find the selection part (when the agents make a selection at the end of the dialogue). Is this expected or I'm missing something? 

Ideally we want it to be similar to openai gym, where at there very end of an episode you are getting a reward.

**Comment by swkrueger** [comment]
This is only the teacher. The learner as well as the functionality for reinforced learning (e.g. rewards) will follow later. The teacher will train the agent to output their selection at the end of an episode after the selection token. For the simulated version, a special World will ensure that this selection is not communicated to the other party.

**Comment by 1nadequacy** [comment]
Makes sense, thanks for the explanation!

**Comment by alexholdenmiller** [comment]
Thanks for checking @1nadequacy! We'll work on the simulated version after adding the model.

**Pull request merged**
