### PR TITLE
Update news for mlb_vqa model

### PR DESCRIPTION
**Pull request by klshuster**

### CODE REVIEW

**Comment by klshuster** [comment]
Ahh yes I realize that the Wikipedia task is not in the "NEWS" yet - I'll add that to this PR in another commit momentarily

**Comment by jaseweston** [comment]
AQUA and Opensubtitles updates also missing i think

**Comment by jaseweston** [comment]
in general where things get added in task list should be explained -- at end? alphabetical? it's a mess.. add to comment at top?

**Comment by alexholdenmiller** [comment]
yeah atm appears to be "wherever you feel like"

**Comment by jaseweston** [comment]
Yea, at least then we could see what we hadn't put news about!

**Comment by jaseweston** [comment]
yes

**Comment by jaseweston** [comment]
yea, messy

**Pull request merged**
