### PR TITLE
[RAG] Fix Extra Positions Bug

### PR DESCRIPTION
**Pull request by klshuster**
**Patch description**
`--n-extra-positions` can be used to expand the total number of positions used when encoding documents + input in pre-trained transformers. If we set this >0, then we are *supposed* to fill up all of end positions with the doc tokens, leaving the beginning positions for the input text. 

In the current RAG implementation, if we specify `--n-extra-positions M` < `--n-positions N`, we encounter an issue where the documents were not properly truncated. This is found in the `concat_docs_and_input` function, where `self.expanded_input_truncate` is used to determine the maximum length of the documents. This is an overloaded attribute, hence why the bug was a bit subtle.

This bug was not previously caught, as in all of my experiments, `--n-extra-positions > --n-positions`. 

**Testing steps**
Added a test to confirm that `concat_docs_and_input` respects the `n_positions` available in the model.

### CODE REVIEW

**Review by mojtaba-komeili — APPROVED** [review]
LGTM

**Comment by mojtaba-komeili** [comment]
nit: a general comment on `self.n_extra_positions`: In `RagModel` constructor we have ` assert opt['n_extra_positions'] >= 0`. Yet there are line in code that we check for `self.n_extra_positions <= 0`.

**Review by jxmsML — APPROVED** [review]
👍

**Comment by klshuster** [comment]
The failing test is fixed in #4395

**Pull request merged**
