### PR TITLE
Include parlai/clib/cuda/ngram_repeat_block_cuda_kernel.*

### PR DESCRIPTION
**Pull request by thandal**
Include parlai/clib/cuda/ngram_repeat_block_cuda_kernel.* files, otherwise I can't seem to build models. For example, 
  parlai.core.agents.create_agent_from_mode_file('zoo:bb3/bb3_3B/model')
fails with
No such file or directory: ../clib/cuda/ngram_repeat_block_cuda.cpp

**Patch description**

**Testing steps**

**Other information**

### CODE REVIEW

**Review by klshuster — APPROVED** [review]
think this looks ok to me

**Review by klshuster — CHANGES_REQUESTED** [review]
could you actually please merge main into this branch first? to make sure tests pass

**Comment by thandal** [comment]
Done

**Review by klshuster — APPROVED** [review]
failing tests are unrelated, thanks!

**Pull request merged**
