### PR TITLE
[WoW] Update teachers to use DialogTeacher

### PR DESCRIPTION
**Pull request by klshuster**
**Patch description**
See title --> updating the WoW teachers to use `DialogTeacher`

**Testing steps**
Banking on CI here

### CODE REVIEW

**Review by mojtaba-komeili — APPROVED** [review]
LGTM. Just make sure you address the lint errors.

**Comment by stephenroller** [comment]
Let's rebase?

**Comment by stephenroller** [comment]
Merge in master

**Comment by klshuster** [comment]
could i please get a quick re-review from either of you @stephenroller @mojtaba-komeili ?

**Pull request merged**
