### PR TITLE
Script for Chatbot using Slack

### PR DESCRIPTION
**Pull request by justquick**
**Patch description**
Adds a new file  `parlai/scripts/interactive_slack.py` that is based on interactive_web but instead communicates with a Slack app bot to observe and act. Just pass the script a bot token and it will do the rest

**Testing steps**
Create a Slack App with legacy bot tokens that can read messages from channels in real time. See here for instructions on creating the app: https://ritikjain1272.medium.com/how-to-make-a-slack-bot-in-python-using-slacks-rtm-api-335b393563cd
Set the bot token env as `SLACK_BOT_TOKEN` or pass `--token` to the script.
Run the following
`parlai interactive_slack --token xoxb-... --task blended_skill_talk:all -mf zoo:blenderbot2/blenderbot2_400M/model --search-server http://localhost:5000/search`
Open a new channel in the slack workspace that you installed the bot in and once it's invited to the conversation (through `@` mention) you can just start talking to it in the channel

**Other information**
I know I probably should have done this in the chat_service providers alongside Telegram/etc but this just seemed easier to me. Depends on the `slackclient` python package
Tested working on BlenderBot 2.0. Screenshots below
Screen Shot 2021-07-20 at 4 36 46 PM

**Search Server**
For BlenderBot 2 i have implemented a domain specific search server in Flask and Elasticsearch to help the slackbot return relevant information. The project can be found below and includes instructions on loading all of the Slack help articles to give the bot some domain specific info about the product. Can be applied to other domain specific indexes (eg company intranet)

https://github.com/spacetelescope/learning/tree/main/chatbot

### CODE REVIEW

**Comment by stephenroller** [comment]
Seems pretty awesome to me.

**Comment by stephenroller** [comment]
Is there any way we could mock the slack client so this is tested?

**Comment by justquick** [comment]
ill see if the slack package has any testing utils otherwise i can  look at mocking it

**Comment by stephenroller** [comment]
Thanks, really excited about this!

**Comment by justquick** [comment]
I added some tests which have 57% coverage of the interactive_slack module. the thing that's missing is the call to the rtm_handler. That requires faking a call from the Slack app when a new message arrives to the local client. Still trying to figure out how that works

Had to add `tests/slack_mock_web_api_server.py` which i copied from the [python-slack-sdk](https://github.com/slackapi/python-slack-sdk/blob/main/tests/rtm/mock_web_api_server.py) client and provides a mock slack client on localhost:8888.

The tests are still failing now because even though ive `mock.patched` the `slack.RTMClient` model, the mock library still requires the `slackclient` package installed so it can know how to fake the methods. I could put it in test_requires but wanted to check with you all first. Currently the tests are failing with this error from `unittest.mock`:

```
    def _importer(target):
        components = target.split('.')
        import_path = components.pop(0)
>       thing = __import__(import_path)
E       ModuleNotFoundError: No module named 'slack'

../../.pyenv/versions/3.8.11/lib/python3.8/unittest/mock.py:1224: ModuleNotFoundError
```

**Pull request closed without merging**
