### PR TITLE
ConvAI server output had changed a bit

### PR DESCRIPTION
**Pull request by madrugado**
could cause troubles with empty responce

### CODE REVIEW

**Comment by stephenroller** [comment]
Not commenting on the actual content of the patch, but the travis fail appears to be lints unrelated to the contributor.

**Comment by alexholdenmiller** [comment]
Can you fix these as well in this patch?
```
projects/convai/convai_world.py:67:89: E501 line too long (89 > 88 characters)
projects/convai/convai_world.py:111:89: E501 line too long (89 > 88 characters)
projects/convai/convai_world.py:177:89: E501 line too long (92 > 88 characters)
projects/convai/convai_world.py:180:89: E501 line too long (115 > 88 characters)
projects/convai/convai_world.py:197:89: E501 line too long (89 > 88 characters)
projects/convai/convai_world.py:198:89: E501 line too long (124 > 88 characters)
projects/convai/convai_world.py:204:89: E501 line too long (106 > 88 characters)
projects/convai/convai_world.py:206:89: E501 line too long (97 > 88 characters)
```

**Comment by madrugado** [comment]
I'm done with code style fixing.

**Comment by alexholdenmiller** [comment]
there's a few more whitespace ones but I'll merge anyways!

**Pull request merged**
