### PR TITLE
minor fixes

### PR DESCRIPTION
**Pull request by Golovneva**
**Patch description**
No actual changes in code

**Testing steps**

**Other information**

### CODE REVIEW

**Comment by Golovneva** [comment]
@klshuster these are not spurious errors, but systematic. I have re-run test on this commits multiple times, still same error in same place: https://app.circleci.com/pipelines/github/facebookresearch/ParlAI?branch=olggol%2Fcomments-4&filter=all
I guess I'll have to wait until someone else finds it out and fixes

**Comment by Golovneva** [comment]
@klshuster It worked, but it required bringing back tensorboard and restricting protobuf instead. I'm surprised people are allowed (i.e. system allows this so easily) to keep merging commits despite tests being broken.

**Comment by Golovneva** [comment]
reopened: https://github.com/facebookresearch/ParlAI/pull/4593

**Comment by klshuster** [comment]
> I'm surprised people are allowed (i.e. system allows this so easily) to keep merging commits despite tests being broken.

We generally enforce (via review) that folks don't break anything with their changes, but this change was not code-driven so slipped through the cracks

**Pull request closed without merging**
