### PR TITLE
Add support for AQuA dataset

### PR DESCRIPTION
**Pull request by apsdehal**
- Partial #492 

So there is a rationale in this dataset which explains the answer. I have currently added to answers' array as second answer. What would be the best way to handle it?

### CODE REVIEW

**Comment by jaseweston** [comment]
You can add it as another field to the observation/action dict (the message sent to the agent). But this would be optional and many models might not use it. Field name 'rationale' perhaps? I'm not sure..

**Comment by jaseweston** [comment]
is this good to check in as is, or do you need to add that stuff @apsdehal ?

**Comment by apsdehal** [comment]
I checked up on the paper @jaseweston. Authors expect the models to generate answer as well as the rationale (so that they can explain how to reached the answers). So, rationale and actual answer are both answers in a way. Let me figure out a way to reflect that.

**Comment by jaseweston** [comment]
could be in the same text field with a '\n' or.. ?  i dont know .. is the rationale text? can you put an example here?

**Comment by apsdehal** [comment]
Yes, rationale is text.
```
Of the 200 students in a school , at least 45 % attended the prom night and at least 35 % took part in the debating session . What is the maximum number of students who could have neither attended the prom night nor the debating session ?

Options: A ) 27|B ) 81|C ) 90|D ) 99|E ) 110

Rationale: To maximize the number of students who did neither , we should minimize the number of students who debated or attended the prom .
Let ' s assume that all 35 % of students who debated also attended the prom .
Then 35 % did both , 10 % only attended prom , and 55 % did neither .
0.55 * 200 = 110
The answer is E .
```

**Comment by apsdehal** [comment]
We can do that, put them together using `\n`.

**Comment by jaseweston** [comment]
How does one evaluate the rationale? it is not multiple choice? you have to
generate a long text like that?

**Comment by apsdehal** [comment]
Yes, kind of like machine translation and evaluated using with average sentence level perplexity and blue 4 score

**Comment by apsdehal** [comment]
You have two answer two things:
- One option among 5 choices for answer
- Rationale explaining your option.

**Comment by jaseweston** [comment]
hmm could do as two responses though because otherwise we can't eval the multiple choice easily... the second one couldnt be a second turn of dialog ('can you explain your answer?' -> rationale reply)

**Comment by apsdehal** [comment]
Yes, that sounds good. I will update the PR accordingly.

**Comment by apsdehal** [comment]
@jaseweston I have updated the PR.

**Comment by alexholdenmiller** [comment]
```
- - - - - - - - - - - - - - - - - - - - -
~~
[AQuA]: Increasing the original price of an article by 5 percent and then increasing the new price by 5 percent is equivalent to increasing the original price by
[labels: A ) 10.25 %]
[cands: A ) 10.25 %|B ) 12.5 %|C ) 14.75 %|D ) 15.15 %|E ) 16.25 %]
   [RepeatLabelAgent]: A ) 10.25 %
~~
[AQuA]: Can you provide a rationale for your answer?
[labels: 1.05 * 1.05 * x = 1.1025 * x
The answer is A .]
[cands: 1.05 * 1.05 * x = 1.1025 * x
The answer is A .]
   [RepeatLabelAgent]: 1.05 * 1.05 * x = 1.1025 * x
The answer is A .
- - - - - - - - - - - - - - - - - - - - -
~~
[AQuA]: How much interest can a person get on Rs . 8200 at 17.5 % p . a . simple interest for a period of two years and six months ?
[labels: C ) 3587.5]
[cands: A ) 3000|B ) 4000.75|C ) 3587.5|D ) 3500|E ) 5020.75]
   [RepeatLabelAgent]: C ) 3587.5
~~
[AQuA]: Can you provide a rationale for your answer?
[labels: I = ( 8200 * 2.5 * 17.5 ) / 100 = ( 8200 * 5 * 35 ) / ( 100 * 2 * 2 ) = Rs . 3587.50
ANSWER C]
[cands: I = ( 8200 * 2.5 * 17.5 ) / 100 = ( 8200 * 5 * 35 ) / ( 100 * 2 * 2 ) = Rs . 3587.50
ANSWER C]
   [RepeatLabelAgent]: I = ( 8200 * 2.5 * 17.5 ) / 100 = ( 8200 * 5 * 35 ) / ( 100 * 2 * 2 ) = Rs . 3587.50
ANSWER C
- - - - - - - - - - - - - - - - - - - - -
```

I notice that for the rationale, we provide a single candidate--the correct answer. Should we remove the candidates instead in the rationale setting?

**Comment by apsdehal** [comment]
I didn't add that. It is how it is in the dataset itself and it actually changes its format with different rationale, so not under our control really.

**Pull request merged**
