### PR TITLE
Add DST teacher for GoogleSGD

### PR DESCRIPTION
**Pull request by jacksukk**
Adding this teacher would allow google_sgd to be usable for Dialog State Tracking task.
cc @chinnadhurai

### CODE REVIEW

**Comment by klshuster** [comment]
could you please run `pytest --force-regen parlai/tasks/google_sgd`?

**Comment by jacksukk** [comment]
> could you please run `pytest --force-regen parlai/tasks/google_sgd/test.py` and then push the updated/autogenerated test files?

Done, thanks for reminding! Let me know if there's anything I can do. :)

**Comment by jacksukk** [comment]
> could you please run `pytest --force-regen parlai/tasks/google_sgd/test.py` and then push the updated/autogenerated test files?

Done, thanks for reminding! Let me know if there's anything I can do

**Comment by klshuster** [comment]
Ahh yes, one more thing: as you've added a new package to `requirements.txt`, you'll need to update the cache key in our [circle config file](https://github.com/facebookresearch/ParlAI/blob/5b2fc1d9c5fb74d4ccb641138cf21765557d78e1/.circleci/config.yml#L210). You can just do a string replace of `'20220805'`

**Comment by jacksukk** [comment]
> Ahh yes, one more thing: as you've added a new package to `requirements.txt`, you'll need to update the cache key in our [circle config file](https://github.com/facebookresearch/ParlAI/blob/5b2fc1d9c5fb74d4ccb641138cf21765557d78e1/.circleci/config.yml#L210). You can just do a string replace of `'20220805'` for each entry to something like `'20220819'`

Done, Thanks!!

**Review by klshuster — APPROVED** [review]
all looks good on my end, thanks!

**Pull request merged**
