### PR TITLE
replace fuzzywuzzy with rapidfuzz

### PR DESCRIPTION
**Pull request by maxbachmann**
**Patch description**
Fuzzywuzzy is GPL licensed, so this PR replaces it with rapidfuzz which is MIT licensed. As a side effect this is much faster, but I do not know whether this is of any relevance in this code section.

**Testing steps**
The behavior should not change.

**Other information**

### CODE REVIEW

**Comment by klshuster** [comment]
Thanks for the PR, could you also please update the [cache keys for our CI](https://github.com/facebookresearch/ParlAI/blob/8b18a15b71d148b7d2a108196115bcc4f025d655/.circleci/config.yml#L234)? 

CC @moyapchen as this is TOD-related (lmk if someone else is better suited for review)

**Comment by maxbachmann** [comment]
@klshuster @moyapchen Is there anything still needed to do from my side?

**Comment by maxbachmann** [comment]
@klshuster @moyapchen is there still interest in this?

**Comment by klshuster** [comment]
yes! could you please update the cache keys one more time?

**Comment by moyapchen** [comment]
Whoops - well, I apparently completely and utterly failed to notice this PR's existence. 

This code is was being used for some of the applied research teams, but I'm pretty sure they've moved far beyond using this teacher a while back, so happy to accept.

**Review by moyapchen — APPROVED** [review]
CC: @skiingpacman just in case

**Pull request closed without merging**
