### PR TITLE
Add length of truncation to logs

### PR DESCRIPTION
**Pull request by spencerp**
**Patch description**
It seems useful to know the average number of tokens truncated when they are truncated. This can't be reliably gleaned from the current metrics, since avg(original_context_length) can be below the truncation length any time context_truncate is below 0.5.

**Testing steps**
Used this in a training run -> Verified the metric showed up in tensorboard

### CODE REVIEW

**Comment by dexterju** [comment]
LGTM, could you expend the test in  test in test_torch_agent.py : https://github.com/facebookresearch/ParlAI/blob/802cec94a4ac027c403b243c8b61d2b967494909/tests/test_torch_agent.py#L1055

**Review by dexterju — APPROVED** [review]
add this to the test plz and you are good to go.

**Review by stephenroller — COMMENTED** [review]
Can you hold until I land the Tensor diff?

**Comment by spencerp** [comment]
> Can you hold until I land the Tensor diff?

Sure! This one, right? https://github.com/facebookresearch/ParlAI/pull/3389

**Pull request merged**
