### PR TITLE
[Wizard of Wikipedia] Interactive retrieval and MTurk evaluation

### PR DESCRIPTION
**Pull request by emilydinan**
Add an interactive retrieval agent that uses a TFIDF retriever to retrieve knowledge to condition on as well as a pre-trained retrieval model, plus a script that allows you to interact with this agent.

Add the M-Turk evaluation task with this model loaded as an example.

### CODE REVIEW

**Comment by stephenroller** [comment]
Fixes #1424

**Comment by emilydinan** [comment]
Thanks @klshuster and @JackUrb -- to make it more clear, I could add a README to the WoW task in the main MTurk directory saying that if you're looking for this task, you'll find it in the projects folder. I will also update the README for the WoW projects folder.

**Comment by abisee** [comment]
Hi @emilydinan, is there a way I can talk to the **generative** WoW model interactively? I tried the following:

`python examples/interactive.py -mf models:wizard_of_wikipedia/end2end_generator/model -t wizard_of_wikipedia`

but that gave the following error:

````
Please choose one of the following topics by typing A, B, C, ..., etc. :

A: Art
B: Graphic design
C: Tokyo
D: Author
E: [NO TOPIC]

Enter Your Message: C
[ Your chosen topic is: Tokyo ]
Enter Your Message: I've never been to Japan, have you?
Traceback (most recent call last):
  File "examples/interactive.py", line 18, in <module>
    interactive(opt, print_parser=parser)
  File "/juice/scr/scr101/scr/abisee/ParlAI/parlai/scripts/interactive.py", line 79, in interactive
    world.parley()
  File "/juice/scr/scr101/scr/abisee/ParlAI/parlai/tasks/wizard_of_wikipedia/worlds.py", line 93, in parley
    self.acts[1] = self.model_agent.act()
  File "/juice/scr/scr101/scr/abisee/ParlAI/parlai/core/torch_agent.py", line 1662, in act
    return self.batch_act([self.observation])[0]
  File "/juice/scr/scr101/scr/abisee/ParlAI/parlai/core/torch_agent.py", line 1683, in batch_act
    batch = self.batchify(observations)
  File "/juice/scr/scr101/scr/abisee/ParlAI/projects/wizard_of_wikipedia/generator/agents.py", line 211, in batchify
    obs_know = self._parse_knowledge(obs)
  File "/juice/scr/scr101/scr/abisee/ParlAI/projects/wizard_of_wikipedia/generator/agents.py", line 172, in _parse_knowledge
    obs['title'], TOKEN_KNOWLEDGE, obs['checked_sentence']
KeyError: 'title'
```

**Comment by stephenroller** [comment]
Hm, thanks for pointing that out. Will you please open a new issue Abi?

**Pull request merged**
