### PR TITLE
Fix map_predictions to be compatible with LM as well as seq2seq

### PR DESCRIPTION
**Pull request by emilydinan**

### CODE REVIEW

**Comment by alexholdenmiller** [comment]
cool for now

**Comment by jaseweston** [comment]
i hope all the other models still work..

**Comment by klshuster** [comment]
As far as i know, this function is currently only used by seq2seq and LM, so it should be fine for now

**Comment by emilydinan** [comment]
@jaseweston yes, definitely only used by seq2seq and LM right now. going to refactor code later so that it just takes an iterable, just need a quick fix for now.

**Pull request merged**
