### PR TITLE
ConvAI: replacing '/start' with 'Your persona:'

### PR DESCRIPTION
**Pull request by madrugado**

### CODE REVIEW

**Comment by madrugado** [comment]
Hi Emily,

Our server also sends a persona in sentences separated by newlines.

**Comment by emilydinan** [comment]
> Hi Emily,
> 
> Our server also sends a persona in sentences separated by newlines.

Great! Is "your persona:" prepended to every persona line?

**Comment by madrugado** [comment]
No, it is only shown once at first line. It should be prepended to each line?

**Comment by madrugado** [comment]
I've checked in the data and made first message compliant with PersonaChat format

**Pull request merged**
