### PR TITLE
[RFC] Initialize TransformerEncoder and TransformerDecoder with opt instead of individual flags

### PR DESCRIPTION
**Pull request by spencerp**
**Patch description**
This is one small step in a larger effort to refactor the transformer code to make it easier to modify and extend. There shouldn't be any functional changes as part of this diff, just organizational.

Some reasons for this change:
- Make these modules less cumbersome to reuse
- Move toward a pattern of using opt (by default) to configure modules instead of explicit values in the code

Let me know if this makes the code more confusing for anyone instead of less!

**Testing steps**
Leaning on the existing unit tests. Will also run some small local runs to sanity check.

### CODE REVIEW

**Review by klshuster — APPROVED** [review]
is there even an argument for *not* using opt here? it's extremely cumbersome otherwise and I readily accept this change. but i'd like to hear other opinions prior to merge.

**Comment by jaseweston** [comment]
having opt all the way down is the good way to go.. in my own use of playing with transformer, i'm doing that..  having opt passed into every module  (e.g. ffn) allows to try experimental flags etc

**Comment by stephenroller** [comment]
Mm one of the disadvantages might be if you use a component outside of the transformer garden, it can be difficult to populate the opt.

The other disadvantage is users may be tempted to set self.opt which can make porting weights more of a pain. We can protect against that though.

Given our goals for this, I agree with using opt.

**Comment by spencerp** [comment]
Abandoning in favor of https://github.com/facebookresearch/ParlAI/pull/3486 which is branched from master instead of `tf-components`.

**Pull request closed without merging**
