### PR TITLE
fix spelling error and add Contributors Avatar in README.md

### PR DESCRIPTION
**Pull request by digger-yu**
**Patch description**
detail info 
1. fix spelling error docs/sample_model_cards/safety_multi/model_card.md on line 71
2. add Contributors Avatar in README.md
    After adjustment
WL7HFRl4Ve

**Testing steps**
Not involved

### CODE REVIEW

**Review by klshuster — CHANGES_REQUESTED** [review]
I think the contributor image is a bit excessive for the main README (is this a thing in other repositories?)

**Comment by digger-yu** [comment]
@klshuster 

This is indeed non-essential, but I think it is an honor for the contributors

**Comment by klshuster** [comment]
Could we maybe have a separate `CONTRIBUTORS.md` file?

**Comment by digger-yu** [comment]
@klshuster 

Yes, most projects I see don't have this separate CONTRIBUTORS.md file, but may have contribution files, including tests, contribution guidelines, CLA, etc. This change is very minor, I just think an open source project putting contributor avatars in the readme.md will increase the honor of the contributors, if you think it's a bit much to put contributor avatars in the readme.md, you can turn off PR

**Comment by klshuster** [comment]
I think the change is a nice one, but it is too much to have on the front page README, which should largely be informative.

**Pull request closed without merging**
