### PR TITLE
fully isolate seq2seq legacy code from rest of parlai

### PR DESCRIPTION
**Pull request by alexholdenmiller**
- move all dependencies from the rest of parlai in legacy seq2seq to a copy in the legacy folder

### CODE REVIEW

**Comment by alexholdenmiller** [comment]
just freezing all the code for this legacy model for reproducibility

**Comment by alexholdenmiller** [comment]
training from scrach on babi:task10k:1 and convai2 scripts work with same old results

**Comment by alexholdenmiller** [comment]
I'm not going to fix the lint errors :)

**Comment by stephenroller** [comment]
party!

**Pull request merged**
