### PR TITLE
set_seed in train_model

### PR DESCRIPTION
**Pull request by prajjwal1**
**Patch description**
Adding a function that allows user to set seed for training. User just has to pass the flag --set_seed with existing arguments to train_model.py in case they want to use a seed other than 42.

**Testing steps**

**Other information**

### CODE REVIEW

**Comment by prajjwal1** [comment]
@stephenroller Can you please look into this ? It has been here for sometime now.

**Comment by prajjwal1** [comment]
I was thinking of using the functionality brought from this to teachers also. Teacher files have `SEED` manually hardcoded to 42. How is a user supposed to set the seed in `Teacher`. This will allow user to bring this functionality to control `rng` in teacher.

**Review by stephenroller — COMMENTED** [review]
I'm fine with this, but I'm pretty sure the existing code already sets the seed. Can we double check?

**Comment by prajjwal1** [comment]
I did check, i didn't find any way to setting the seed universally. I plan to send one more PR for `multiwoz_v22`, which will set the `rng` through `opt`. Current `opt` dict doesn't have it, so where else is `seed` parameter supposed to go ?

**Comment by klshuster** [comment]
> I'm fine with this, but I'm pretty sure the existing code already sets the seed. Can we double check?

interestingly I can't seem to find it either. we set seeds in nearly every other script except for train model

pure non-determinism! In that case, can we have the default seed be `None` and only set seed if it's not `None`?

**Comment by prajjwal1** [comment]
Default way is to set the seed to 42 right ? Can I set it to 42, and this can be overridden by the user by passing in `--seed` parameter ? By not setting the seed, users are likely to observe variability in their training runs.

**Comment by stephenroller** [comment]
> > I'm fine with this, but I'm pretty sure the existing code already sets the seed. Can we double check?
> 
> interestingly I can't seem to find it either. we set seeds in nearly every other script except for train model
> 
> pure non-determinism! In that case, can we have the default seed be `None` and only set seed if it's not `None`?

ah right this is what i misremembered

**Comment by stephenroller** [comment]
> Default way is to set the seed to 42 right ? Can I set it to 42, and this can be overridden by the user by passing in `--seed` parameter ? By not setting the seed, users are likely to observe variability in their training runs.

historically we've preferred backwards compatibility

**Comment by klshuster** [comment]
I agree, let's keep it to None. We've advocated for variability from the start

**Comment by prajjwal1** [comment]
@klshuster Is it fine now ?

**Review by stephenroller — APPROVED** [review]
lgtm, will leave Kurt for final approval and merge

**Review by klshuster — APPROVED** [review]
thank you!

**Pull request merged**
