### PR TITLE
Update Hallucination README.md

### PR DESCRIPTION
**Pull request by klshuster**
**Patch description**
Per #3872, we should include the `--model-file` parameter in the example training commands for the Hallucination project

### CODE REVIEW

**Comment by jianguoz** [comment]
> **Patch description**
> Per #3872, we should include the `--model-file` parameter in the example training commands for the Hallucination project

Per #3881 and #3873. Maybe we can merge them together later. In #3881, the model should immediately raise an `AssertionError` when there are `NaN` instead of logging errors and replacing `NaN` with other values. Besides, after careful investigation, I found the `NaN` error is not caused by either `--indexer-type exact` or `--indexer-type compressed.` The error comes from [num_shards](https://github.com/facebookresearch/ParlAI/blob/master/parlai/agents/rag/scripts/generate_dense_embeddings.py#L190). Where if end_idx<n_docs, it will raise `NaN` error. So it is better to set `--num-shards` to small values. For example, if `--shard-id` is 0, then `--num-shards is a value < int(len(rows of the passages file)/(n_maximum_passages_you_want_to_retrieve-1))`. In #3873, I will slightly update the readme soon to give more instructions.

**Comment by klshuster** [comment]
Hi @jianguoz, though I appreciate the changes you have proposed, these seem more suitable for a separate PR (as now I cannot actually review the changes you've made)

**Comment by jianguoz** [comment]
> Hi @jianguoz, though I appreciate the changes you have proposed, these seem more suitable for a separate PR (as now I cannot actually review the changes you've made)

@klshuster  Sure! I will do it:).

**Review by spencerp — APPROVED** [review]
lgtm!

**Pull request merged**
