### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by tanujdhiman**
Error facing when installing all requirements !

parlai

### CODE REVIEW

**Comment by mojtaba-komeili** [comment]
I am not sure if this is needed. Are you sure your `pip` is configured properly? 7.19.0 is a valid `ipython` version (check [this](https://pypi.org/project/ipython/7.19.0/)). Could you try removing `ipython` and trying again?

**Comment by tanujdhiman** [comment]
Yes pip is properly upgraded. Actually what happens is that version is not matching with `ipython` version. And also if there we remove `ipython` then it will automatically download the version `7.16.1` 

That's why I changed the version of ipython. 

Hope you understand!! 

Thanks

**Comment by mojtaba-komeili** [comment]
There is no issue like that if you start with a clean environment, for example new conda env (I just tried that myself). The problem seems to be from some other packages that you have in your environment. Please check for other conflicting packages.

**Comment by tanujdhiman** [comment]
Oh I see!

I was trying it in my existing env now it is working for me too.
Thanks

**Pull request closed without merging**
