### PR TITLE
Update tokens/batch metrics a bit.

### PR DESCRIPTION
**Pull request by stephenroller**
**Patch description**
Add some additional token-per-batch metrics: tpb_t and tpb_l which are text_vec tokens/batch and label_vec tokens/batch . The old tpb changes its semantics from label tokens/batch to tokens/batch including BOTH label and text.  We also add an "examples/batch" metric which is nice when using dynamic batching.

**Testing steps**
Manual testing. CI.

### CODE REVIEW

**Comment by stephenroller** [comment]
Yes to confusing, but no to breaking anything. This is only reported. If y'all have suggestions for better name, i'm down to hear.

The reason was just because it was useful to me lol.

**Comment by EricMichaelSmith** [comment]
Hmm, I suppose you could do 'total_tokens_per_batch', 'text_tokens_per_batch', and 'label_tokens_per_batch' - up to you, though

**Comment by stephenroller** [comment]
My feeling was those were just tooooo long.

**Comment by stephenroller** [comment]
Decided we don't really need this, I identified what I needed to and Eric's right, the confusion is unnecessary.

**Pull request closed without merging**
