### PR TITLE
[BERT Classifier] CLS + SEP tokens, plus segments

### PR DESCRIPTION
**Pull request by emilydinan**
**Patch description**
- Add option to add CLS token to the front of the text_vec. This defaults to True. We keep it as an option for backwards compatibility as some models were not doing this before. (Note: old models will still break unless we set the flag correctly, which is a tradeoff.)
- Add option to separate the last utterance in the history: adds a separator token and uses a different segment index for these tokens.
- Also add option to pass in a list to BERT's dictionary `vec2txt` function.

**Testing steps**
Train models.

### CODE REVIEW

**Comment by stephenroller** [comment]
This is exactly the kind of thing we need upgrade_opt for

**Comment by samhumeau** [comment]
It looks good to me, (but the non backward compatibility is a bit annoying. Maybe a 'version' attribute?)

**Comment by emilydinan** [comment]
> It looks good to me, (but the non backward compatibility is a bit annoying. Maybe a 'version' attribute?)

good idea -- i'll fix

**Comment by emilydinan** [comment]
thoughts about this backwards compatibility fix @stephenroller @samhumeau ?

**Pull request merged**
