### PR TITLE
More tests

### PR DESCRIPTION
**Pull request by mojtaba-komeili**
**Patch description**
* Another try for turning them green.
* Upgraded the deprecated CircleCI image that was running our tests.

### CODE REVIEW

**Comment by klshuster** [comment]
which tests should this be turning green? i.e., cleaninstall and unittests_38 still red?

**Comment by mojtaba-komeili** [comment]
> which tests should this be turning green? i.e., cleaninstall and unittests_38 still red?

Yeah, I think `cleaninstall` is what causes the issue with the others too. There is some version conflict betweeen torch, torchvision and torchtext which looks impossible to solve.

**Comment by klshuster** [comment]
> Yeah, I think `cleaninstall` is what causes the issue with the others too. There is some version conflict betweeen torch, torchvision and torchtext which looks impossible to solve.

There is some logic in how to assign versions 

can you try these? this is my current env:

```
torch                    1.13.1
torchaudio               0.13.1
torchvision              0.14.1
```

**Comment by mojtaba-komeili** [comment]
OK, thanks. That was the magic combination. It cleaned up the clean install. Now four unit test are failing apex (1) and starspace (3). I would say let's merge these and work on those in another PR?

**Comment by klshuster** [comment]
yep, so i already know the apex issue

pytorch 1.13.1 has an issue where `torch.load` doesn't respect custom pickle modules, so it's breaking when a model is loaded that we trained a while ago when apex was installed

for now, we may need to just mark that test as skippable if the pytorch version is 1.13.1

**Review by klshuster — APPROVED** [review]

**Pull request merged**
