### PR TITLE
Add support for Palm, Claude-2, Cohere, Sagemaker, Bedrock (100+LLMs)

### PR DESCRIPTION
**Pull request by ishaan-jaff**
**Patch description**

This PR adds support for the above mentioned LLMs using LiteLLM https://github.com/BerriAI/litellm/ 
LiteLLM is a lightweight package to simplify LLM API calls - use any llm as a drop in replacement for gpt-3.5-turbo. 

Example
```python
from litellm import completion

## set ENV variables
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["COHERE_API_KEY"] = "cohere key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion(model="command-nightly", messages)

# anthropic call
response = completion(model="claude-instant-1", messages=messages)
```

**Testing steps**

**Other information**

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
@mojtaba-komeili @klshuster can i get a review on this PR ? 

happy to add docs/ tests if this initial commit looks good

**Comment by mojtaba-komeili** [comment]
I am not sure if the litelm package had wide enough adoption to justify adding that to our packages. Perhaps for now it makes sense to keep is as part of an external branch.

**Comment by ishaan-jaff** [comment]
Hi @mojtaba-komeili following up on this - LiteLLM has 2.5K stars, used by 290+ open source projects. We'd love to create value for this package 

We make it very easy to evaluate LLMs

**Comment by mojtaba-komeili** [comment]
OK, let's merge this in.

**Review by mojtaba-komeili — APPROVED** [review]

**Pull request merged**
