### PR TITLE
Add SPOLIN as a ParlAI Teacher 

### PR DESCRIPTION
**Pull request by wise-east**
**Patch description**

Adding a ParlAI Teacher for the dataset [SPOLIN](https://justin-cho.com/spolin), which is the dataset from [_Grounding Conversations with Improvised Dialogues_](https://aclanthology.org/2020.acl-main.218/) (ACL 2020)

SPOLIN is a dataset of conversation pairs that abide by the Yes-and principle of improvisational theatre (improv).

**Testing steps**
All steps in the official documentations were taken: https://parl.ai/docs/tutorial_task.html#creating-a-new-task-the-more-complete-way 

Downloading and displaying the data: 
`parlai dd -t spolin`

pytest command: 
`python -m pytest  parlai/tasks/spolin/test.py`

### CODE REVIEW

**Review by stephenroller — APPROVED** [review]
This looks all great!

**Comment by stephenroller** [comment]
You need to Black, Lint, and sign the CLA.

**Comment by stephenroller** [comment]
The teacher test failure is a known issue unrelated to your PR.

**Comment by stephenroller** [comment]
It looks like lint and black are still failing. Can you click on the Details of those and take a look?

**Comment by wise-east** [comment]
I think I fixed lint and black failing. Not sure what happened for `crowdsourcing_tests`. I couldn't make out the error message for this one. Maybe rerunning it work since it says it's a connection error, but I don't think I'm authorized to rerun that test.

**Comment by stephenroller** [comment]
Crowdsourcing one is surely flaky.

**Comment by wise-east** [comment]
Finally made it through! except for the teacher_tests

**Comment by wise-east** [comment]
@stephenroller Let me know if there is anything else I can do to get this pull request get through

**Comment by stephenroller** [comment]
Thanks for the reminder and the contribution.

**Pull request merged**
