### PR TITLE
Tutorial for Adding Cuda C++ Kernel to ParlAI with Examples

### PR DESCRIPTION
**Pull request by pearlli98**
add tutorial on how to add a custom cuda C++ kernel to ParlAI

### CODE REVIEW

**Comment by klshuster** [comment]
were you able to build the website locally and have this display? see [here](https://github.com/facebookresearch/ParlAI/tree/main/docs) for how to do so

**Comment by klshuster** [comment]
cc @dexterju27 since I believe @pearlli98 is not able to complete this PR?

**Comment by dexterju27** [comment]
I'll take a look next week.

**Comment by dexterju27** [comment]
@klshuster  The html build error is fixed.

**Comment by klshuster** [comment]
could you also please merge `main` into this branch? to pass tests

**Pull request closed without merging**
