### PR TITLE
Fix a few lint errors

### PR DESCRIPTION
**Pull request by stephenroller**
**Patch description**
Small stuff that made it through at some point.

### CODE REVIEW

**Comment by stephenroller** [comment]
```
There are 166787 missing_labels in wizard_of_wikipedia:WizardOfWikipediaTeacher.
F
======================================================================
FAIL: test_verify_data (__main__.TestNewTasks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/datatests/test_new_tasks.py", line 70, in test_verify_data
    self.assertFalse(found_errors, "Errors were found.")
AssertionError: True is not false : Errors were found.

----------------------------------------------------------------------
Ran 1 test in 756.354s

FAILED (failures=1)
python tests/datatests/test_new_tasks.py
```

Looks like wiz fails but it seems intentional? I'm thinking we might want to make teachers that start with a `_` immune to the test and then rename this teacher. Also file an issue.

**Comment by EricMichaelSmith** [comment]
> ```
> There are 166787 missing_labels in wizard_of_wikipedia:WizardOfWikipediaTeacher.
> F
> ======================================================================
> FAIL: test_verify_data (__main__.TestNewTasks)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "tests/datatests/test_new_tasks.py", line 70, in test_verify_data
>     self.assertFalse(found_errors, "Errors were found.")
> AssertionError: True is not false : Errors were found.
> 
> ----------------------------------------------------------------------
> Ran 1 test in 756.354s
> 
> FAILED (failures=1)
> python tests/datatests/test_new_tasks.py
> ```
> 
> Looks like wiz fails but it seems intentional? I'm thinking we might want to make teachers that start with a `_` immune to the test and then rename this teacher. Also file an issue.

The failure here is expected because the base `WizardOfWikipediaTeacher` doesn't return a label field, right? Yeah, I'm definitely in favor of some kind of signifier to prevent this kind of teacher from being checked by this unit test. A `_` might work, but I'm not sure a priori if it's always the case that an incomplete teacher == a private teacher

**Comment by stephenroller** [comment]
> The failure here is expected because the base `WizardOfWikipediaTeacher` doesn't return a label field, right? Yeah, I'm definitely in favor of some kind of signifier to prevent this kind of teacher from being checked by this unit test. A `_` might work, but I'm not sure a priori if it's always the case that an incomplete teacher == a private teacher

Maybe we should discuss? It seems that an incomplete teacher also shouldn't be used by models etc, so marking it private would be trying to avoid that.

**Comment by EricMichaelSmith** [comment]
> > The failure here is expected because the base `WizardOfWikipediaTeacher` doesn't return a label field, right? Yeah, I'm definitely in favor of some kind of signifier to prevent this kind of teacher from being checked by this unit test. A `_` might work, but I'm not sure a priori if it's always the case that an incomplete teacher == a private teacher
> 
> Maybe we should discuss? It seems that an incomplete teacher also shouldn't be used by models etc, so marking it private would be trying to avoid that.

Yeah, I can't immediately think of any cases in which we'd *need* to use an incomplete teacher, so I'm fine making the implicit equivalence between "private teacher" and "teacher we don't run this test for"

**Pull request merged**
