### PR TITLE
[SeeKeR] Fix Tests

### PR DESCRIPTION
**Pull request by klshuster**
**Patch description**
Fix broken seeker test

**Testing steps**
CI

### CODE REVIEW

**Review by stephenroller — APPROVED** [review]

**Comment by klshuster** [comment]
so the natural questions teacher tests are failing because we don't require a `google-cloud-storage` install; would you prefer I add that to the CI config to install, or to `requirements.txt`?

**Review by mojtaba-komeili — APPROVED** [review]

**Comment by stephenroller** [comment]
Either works I guess. Requirements is probably more standard.

**Comment by klshuster** [comment]
ok, added to requirements and bumped cache. will merge if all tests pass

**Comment by mojtaba-komeili** [comment]
Checkout their sample subset linked above the main dataset links for testing ([link](https://storage.cloud.google.com/natural_questions/v1.0/sample/nq-train-sample.jsonl.gz)).

**Pull request merged**
