### PR TITLE
Flake8 the code

### PR DESCRIPTION
**Pull request by stephenroller**
This is hardly all the warnings, but it eliminates all the flake8 errors, and a good chunk of the style warnings.

Proposing we make `flake8 --select=F parlai projects tests` commit blocking in the travis script.

### CODE REVIEW

**Comment by JackUrb** [comment]
❤️

**Comment by stephenroller** [comment]
Gonna stop here, there's more than can be done, but this is good for now.

**Comment by alexholdenmiller** [comment]
if `flake8 --select=F parlai projects tests`, happy to have you submit a diff to update the travis yml!

**Comment by stephenroller** [comment]
Opting to rebase in hopes that it will make rebases, merges, and bug tracks easier.

**Pull request merged**
