### PR TITLE
Add metacognition project code and (link to) data to projects

### PR DESCRIPTION
**Pull request by sjmielke**
Code and (through external link) data release for FAIR paper "Reducing conversational agents' overconfidence through linguistic calibration" (older version at https://arxiv.org/abs/2012.14983 ) in preparation of TACL final version upload.

### CODE REVIEW

**Comment by stephenroller** [comment]
Let's pull the sweeps out, as they won't run externally.

**Comment by stephenroller** [comment]
I've reported the bot internally

**Comment by sjmielke** [comment]
Added commit that removes the sweep files.

**Comment by emilydinan** [comment]
moved to #4500

**Pull request closed without merging**
