### PR TITLE
fixing minor issues rebased

### PR DESCRIPTION
**Pull request by Golovneva**
**Patch description**
Adding/fixing comments. Fixing main to make it pass tests.

**Testing steps**

**Other information**

### CODE REVIEW

**Comment by klshuster** [comment]
We removed the `tensorboard` from `requirements.txt` yesterday, and I think this fixes the `cleaninstall` issues; thus, I'm not sure this PR is necessary anymore

**Comment by Golovneva** [comment]
> We removed the `tensorboard` from `requirements.txt` yesterday, and I think this fixes the `cleaninstall` issues; thus, I'm not sure this PR is necessary anymore

Not sure what do you mean. Main is failing. You can also look at previous runs in this commit thread on latest main, they are all failing. `tensorboard` removal introduced new breakages

**Comment by klshuster** [comment]
i think those are spurious errors; it seems that #4590 had passing tests when it was landed

**Comment by Golovneva** [comment]
Will create a PR with text changes only

**Review by klshuster — APPROVED** [review]
approving given everything passes. Thanks!

**Comment by Golovneva** [comment]
Huh, still failed in mainline. Is it possible that some other changes are required in circleci config?

**Pull request merged**
