### PR TITLE
Increase CI parallelism

### PR DESCRIPTION
**Pull request by stephenroller**
**Patch description**

**Testing steps**

**Other information**

### CODE REVIEW

**Review by klshuster — APPROVED** [review]

**Comment by klshuster** [comment]
any reason we're waiting to merge this?

**Comment by klshuster** [comment]
@stephenroller should we just close this?

**Comment by stephenroller** [comment]
I don't think it fixes the root issue but sure, merging isn't worse than main already is.

**Comment by stephenroller** [comment]
I don't think it fixes the root issue but sure, merging isn't worse than main already is.

**Pull request merged**
