### PR TITLE
Add regular dropout (like fairseq).

### PR DESCRIPTION
**Pull request by stephenroller**
Equivalent to `--dropout` in fairseq. This dropout apparently works a bit better for very large datasets.

### CODE REVIEW

**Comment by stephenroller** [comment]
@samhumeau I believe you requested embedding dropout at some point

**Comment by samhumeau** [comment]
Do we need to be that precise? Can we just have relu_dropout == dropout here?

**Comment by stephenroller** [comment]
I'd prefer to keep the consistency with fairseq and tensor2tensor. @myleott also says he may sometimes tunes all 3 separately when learning on small datasets.

**Comment by myleott** [comment]
Also, in the original AIAYN paper relu_dropout and attn_dropout were zero, but dropout was non-zero :)

**Pull request merged**
