### PR TITLE
Setup code coverage

### PR DESCRIPTION
**Pull request by vedantpuri**
**Patch description**
Introduce code coverage for ParlAI. Solves #1880 

**Testing steps**
Run
```
 coverage run setup.py test
```
and then run
```
coverage report
```

**Logs**
Truncated terminal output (of the second command):
```
Name                                                             Stmts   Miss  Cover
------------------------------------------------------------------------------------
examples/display_data.py                                             8      4    50%
examples/eval_model.py                                               6      3    50%
parlai/agents/legacy_agents/seq2seq/dict_v0.py                     361    196    46%
parlai/agents/legacy_agents/seq2seq/modules_v0.py                  408    211    48%
parlai/agents/legacy_agents/seq2seq/seq2seq_v0.py                  446    249    44%
parlai/agents/legacy_agents/seq2seq/utils_v0.py                    359    225    37%
parlai/agents/memnn/memnn.py                                       114     27    76%
parlai/agents/memnn/modules.py                                      82     15    82%
parlai/agents/random_candidate/random_candidate.py                  30      5    83%
.
.
.
tests/test_seq2seq.py                                               40      1    98%
tests/test_ta_inheritence.py                                        34      1    97%
tests/test_teachers.py                                              24      1    96%
tests/test_tfidf_retriever.py                                       47      3    94%
tests/test_tga.py                                                   27      1    96%
tests/test_threadutils.py                                           82     17    79%
tests/test_torch_agent.py                                          516      3    99%
tests/test_tra.py                                                  104      1    99%
tests/test_train_model.py                                           21      1    95%
tests/test_transformers.py                                         121      1    99%
tests/test_utils.py                                                 98      2    98%
tests/test_zootasks.py                                              57      5    91%
------------------------------------------------------------------------------------
TOTAL                                                            13559   3921    71%
```

**Other information**
N/A

**Data tests (if applicable)**
N/A

### CODE REVIEW

**Comment by stephenroller** [comment]
Okay I'm going to commandeer this diff, thanks @vedantpuri.

**Comment by vedantpuri** [comment]
Great! I am excited to have been a part of this! Also, would appreciate if you had a look at one of my comments on the related issue! I had some thoughts about xml v.s. html reporting!
The comment is [here](https://github.com/facebookresearch/ParlAI/issues/1880#issuecomment-548181826)

**Comment by stephenroller** [comment]
Report seems uploaded to codecov.io successfully, generated the report well.

Can anyone else see this? You will probably need to log into codecov.io using your github account:

https://codecov.io/gh/facebookresearch/ParlAI/commit/eaaa61fb0674ad0af73b5d44884e54a45d4bc232

Unfortunately, codecov bot didn't post on this PR which is #sad.

@vedantpuri is going to look into making sure nontouched files are also recorded in report.

**Comment by stephenroller** [comment]
Screen Shot 2019-10-31 at 10 19 31 AM

Screenshot

**Comment by stephenroller** [comment]
That's exactly what we wanted! It looks like you haven't actually pushed the change to the config though.

**Comment by vedantpuri** [comment]
Just pushed!

**Comment by stephenroller** [comment]
(Attempting long tests, then we should merge fast so we start collecting for master.)

**Pull request merged**
