### PR TITLE
[Bug Fix]Display data should add :ordered properly

### PR DESCRIPTION
**Pull request by dexterju**
**Patch description**
The previous code forces display_data to have ordered in opt, this logic breaks for valid, test. Also breaks for train:stream
**Testing steps**
display_data with any chunk teacher.

### CODE REVIEW

**Comment by stephenroller** [comment]
@emilydinan  is this what you were thinking?

**Comment by dexterju** [comment]
Ping.

**Comment by stephenroller** [comment]
Merge in master and rerun checks. This kind of change could be insidious and 4 checks flagging looks weird

**Comment by dexterju** [comment]
Yes, I tested with valid:stream and test:stream

**Comment by dexterju** [comment]
The unittests_38 is broken, right?

**Comment by stephenroller** [comment]
Yeah that’s just a fluke

**Pull request merged**
