### PR TITLE
Normalized all convai2 teachers

### PR DESCRIPTION
**Pull request by jxmsML**
**Patch description**
Add variants of convai2 teacher

- Normalize all convai2 teachers (None, Both, Self, Their)
- Add `--your-persona-first`: whether to prepend your persona first or their persona (which matter if context_truncate is smaller than the persona length); default is true (consistent with the original `BothTeacher`)
- Add `--max-num-turns`: first `max_num_turns` per episode to show if persona is increasingly/decreasingly important. default is `-1` meaning no truncation.
- Add `TheirTeacher`: only prepend partner's persona

**Testing steps**
CI
``` parlai dd -t convai2:NormalizedBoth```
```
- - - NEW EPISODE: convai2:NormalizedBoth - - -
your persona: My mom is my best friend.
your persona: I have four sisters.
your persona: I believe that mermaids are real.
your persona: I love iced tea.
partner's persona: I wish I could live forever.
partner's persona: I only date people taller than me.
partner's persona: I really like technology.
partner's persona: I like free diving.
Hi, how are you doing today?
   I am spending time with my 4 sisters what are you up to
Wow, four sisters. Just watching game of thrones.
   That is a good show I watch that while drinking iced tea
I agree. What do you do for a living?
   I'm a researcher I'm researching the fact that mermaids are real
23:07:28 | loaded 17878 episodes with a total of 131438 examples
```

```
parlai dd -t convai2:NormalizedBoth --your-persona-first False -ne 20  --max-num-turns 1

- - - NEW EPISODE: convai2:NormalizedBoth - - -
partner's persona: I went to school for fashion design and did nothing with it.
partner's persona: I'ven t had to work a day in my life.
partner's persona: I don t know why my sister in law dislikes me.
partner's persona: I think I need botox soon.
your persona: I watch a lot of tv.
your persona: I live alone.
your persona: I enjoy fishing.
your persona: I work on cars for a living.
Hello, tell me about you.
   Hi, I am a mechanic who lives alone... How about you?
- - - NEW EPISODE: convai2:NormalizedBoth - - -
partner's persona: I really like watching star trek.
partner's persona: I like eating pretzels.
partner's persona: My favorite band is vnv nation.
partner's persona: I work for the railroad.
your persona: I like to hunt.
your persona: Both my parents were teachers.
your persona: I had two cats growing up.
your persona: I have two children.
your persona: I like to donate time at the local animal shelter.
Hey whats going on? How are you?
   Not much, just seen both my children off to school, you?
20:59:34 | loaded 17878 episodes with a total of 17878 examples
```

```
parlai dd -t convai2:NormalizedTheir --max-num-turns -1
- - - NEW EPISODE: convai2:NormalizedTheir - - -
partner's persona: I wish I could live forever.
partner's persona: I only date people taller than me.
partner's persona: I really like technology.
partner's persona: I like free diving.
Hi, how are you doing today?
   I am spending time with my 4 sisters what are you up to
Wow, four sisters. Just watching game of thrones.
   That is a good show I watch that while drinking iced tea
I agree. What do you do for a living?
   I'm a researcher I'm researching the fact that mermaids are real
21:02:46 | loaded 17878 episodes with a total of 131438 examples
```
**Other information**

### CODE REVIEW

**Review by stephenroller — APPROVED** [review]

**Review by stephenroller — COMMENTED** [review]
Would be a cool use for mutators

**Comment by jxmsML** [comment]
> Would be a cool use for mutators

what do you mean @stephenroller

**Comment by stephenroller** [comment]
I mean you're doing the same transformation on multiple datasets. That's fine and easy here, but it's also the use case of mutators exactly.

**Comment by jxmsML** [comment]
> I mean you're doing the same transformation on multiple datasets. That's fine and easy here, but it's also the use case of mutators exactly.

yea. The main thing I want to mutate here is the positions of your persona + their persona, but I also find it very specific in this case that as far as I know it only applies to this convai2 teacher?

**Comment by stephenroller** [comment]
The normalization part (punctuation/casing) is pretty agnostic. Anyway this is all fine, I'm just trying to encourage thinking about the new tool in the toolbox.

**Review by stephenroller — APPROVED** [review]

**Pull request merged**
