### PR TITLE
Move shared_utils and server_utils to chat_service/core/

### PR DESCRIPTION
**Pull request by young-k**
**Patch description**

Neither `shared_utils` nor `server_utils` is messenger-implementation specific, so I moved them to `core/`. 

**Testing steps**

~CircleCI :pray:~ will look into better ways to test this

**Other information**

N/A

### CODE REVIEW

**Comment by stephenroller** [comment]
Is circleci really testing that part of the code? I'm not sure we have tests over there.

**Comment by stephenroller** [comment]
Ignore codecov bot, it's confused lol.

**Comment by stephenroller** [comment]
What's going on here.

**Comment by klshuster** [comment]
oh let me just merge this, forgot to do that

**Pull request merged**
