### PR TITLE
Personachat paper: add mturk evaluations, language model trained on opensubtitles 2018, data collection task to mturk

### PR DESCRIPTION
**Pull request by emilydinan**
Sample files for how we used Mechanical Turk for human evaluation of our models in the personachat paper.

### CODE REVIEW

**Comment by emilydinan** [comment]
@jaseweston this is just the Turk job to compare models. I can add one for the original data collection, but the instructions would be quite similar (just replace the model with another MTurk agent essentially).

**Comment by jaseweston** [comment]
cool, yes adding that would be most good.

**Comment by emilydinan** [comment]
added script to interact with language model trained on Opensubtitles2018. added a flag to language model that allows for sampling of distribution during interactive mode (and does not produce UNK token)

**Comment by emilydinan** [comment]
Added personachat data collection task to parlai/mturk/tasks

**Comment by emilydinan** [comment]
Changed the scripts for interacting with pretrained models so that we build using parlai `build_data` tools; this involved a small change to `examples/interactive.py`

**Comment by emilydinan** [comment]
@jaseweston merging now!

**Pull request merged**
