### PR TITLE
[Bug FIx]Rouge metrics are computed but not reported.

### PR DESCRIPTION
**Pull request by dexterju**
**Patch description**
As stating in the title.
**Test**
Run any eval_model with --metrics all

### CODE REVIEW

**Comment by stephenroller** [comment]
This was supposed to be done by the block below which iterates through everything in metrics_list.

**Comment by stephenroller** [comment]
I still feel like the root cause is off, not the actual code below that is supposed to be doing this computation.

**Comment by stephenroller** [comment]
Let's revisit this.

**Comment by klshuster** [comment]
This was handled in #2116, closing

**Pull request closed without merging**
